### ISSUE TITLE
Redis URL format compatible with python-redis

### ISSUE THREAD

**Issue by ThiefMaster** [alisaifee/limits#128]
I just received this "bug" report in my application: indico/indico#5391

Would you consider making your URL format compatible with the one [redis-py](https://pypi.org/project/redis/) uses? I'd rather not convert between two URL formats if I can avoid it...

**Comment by alisaifee** [comment]
Unfortunately having the `redis` prefix in all schemes for redis like storages (including cluster, sentinel etc) isn't something that can be easily decoupled from the design (especially since flask limiter and other similar libraries are coupled to it).

I can suggest a small workaround. From looking at your code it looks like you only intend to support single instance redis' as the rate limiting backend (i.e. not intending to support redis cluster or sentinel managed redis').

You could create a custom storage that extends the `limits.storage.RedisStorage` and it'll automatically get added to the storage registry:

```py
class IndicoRedisStorage(limits.storage.RedisStorage):
    STORAGE_SCHEME = ["redis", "rediss", "unix"]

assert isinstance(
    limits.storage.storage_from_string("unix:///tmp/indico.sock"), 
    limits.storage.RedisStorage
)
```

**Comment by ThiefMaster** [comment]
works fine, thanks!
