### ISSUE TITLE
Exponential / growing limits

### ISSUE THREAD

**Issue by mtvx** [alisaifee/limits#161]
Hey hey, I've used the library through `Flask-Limiter` but never got deep into it 😄

Trying to check if configuring an exponential/growing limit is possible, ie. limiting that gets prolonged if the caller keeps on bombarding.

Are you / would you support something like this? If yes/no, why?

**Comment by alisaifee** [comment]
Though not exactly what you've described, there is a [Fixed Window with Elastic Expiry](https://limits.readthedocs.io/en/latest/strategies.html#fixed-window-with-elastic-expiry). This hasn't been touched since the library was created since I didn't really flesh it out very well but could be worth using as a starting point.

**Comment by mtvx** [comment]
Right. I'll look into it 👍🏻
