### ISSUE TITLE
any idea what's happening here? LockError: Cannot release an unlocked lock

### ISSUE THREAD

**Issue by thestick613** [alisaifee/limits#6]
I'm running a pretty big stress test with redis+sentinel and this popped up:

      File "/root/venv_smtpin/local/lib/python2.7/site-packages/limits/strategies.py", line 76, in hit
        item.get_expiry()
      File "/root/venv_smtpin/local/lib/python2.7/site-packages/limits/storage.py", line 456, in acquire_entry
        key, limit, expiry, master, no_add
      File "/root/venv_smtpin/local/lib/python2.7/site-packages/limits/storage.py", line 294, in acquire_entry
        return True
      File "/root/venv_smtpin/local/lib/python2.7/site-packages/redis/lock.py", line 88, in __exit__
        self.release()
      File "/root/venv_smtpin/local/lib/python2.7/site-packages/redis/lock.py", line 133, in release
        raise LockError("Cannot release an unlocked lock")
    LockError: Cannot release an unlocked lock

I'm firing up a lot of gevent workers on this and i'm just forcing a lot of hits upon a small moving window.

**Comment by alisaifee** [comment]
Hi @thestick613 .. I faced this problem while running one of the unit tests once in a while.  The error is correct, but partially misleading due to a minor bug in the `redis-py` lock implementation ([issue](https://github.com/andymccurdy/redis-py/pull/661)). If you look at the use of the lock [here](https://github.com/alisaifee/limits/blob/master/limits/storage.py#L283) you'll notice that theres a 1 second timeout on blocking to acquire the lock. I'm going to guess that you've got one individual route being accessed at a rate where redis can't keep up with locking in place.

**Comment by thestick613** [comment]
Wouldn't a rate limiting implementation based on a internal redis script written in lua make more sense? It wouldn't need an external locking mechanism.

**Comment by alisaifee** [comment]
@thestick613 : yes I think if we move the interaction with redis in the [`acquire_entry`](https://github.com/alisaifee/limits/blob/master/limits/storage.py#L270) method into a single lua script and remove the lock around it, the rate limiting logic would still be equivalent. Since you already have a good test case that demonstrates this problem, I'd appreciate any help with this.

**Comment by alisaifee** [comment]
@thestick613: I've got an implementation using the lua method you suggested in the branch `no-redis-lock`. If you get a chance to take it for a test drive against your stress tests, please share the outcome.

**Comment by thestick613** [comment]
I'll test it asap. It now looks like all the logic is moved inside two LUA scripts right?
BTW, I keep wondering why these very common scenarios aren't moved inside redis core:
- distributed network lock
- rate limit with moving window or static window
- expire hash keys with TTL
etc. There are over 100 git repos implementing these things in all available languages, even in LUA. :/

**Comment by thestick613** [comment]
On the last version, this is able to generate the timeout. You can try it yourself, if you feel like it:
        
    from sentinel_rate_limiter import CustomRateLimiter
    import time
    import gevent
    
    from multiprocessing import cpu_count
    from multiprocessing.pool import Process
    
    def worker(mlr):
        ok = 0
        for _ in range(1,1000):
            if mlr.hit('samekey'):
                ok += 1
                print "*",
            else:
                print "_",
            time.sleep(0.000001)
        return ok
    
    def task():
        tasks = []
        mlr = CustomRateLimiter()
    
        for _ in range(1,1000):
            tasks.append(gevent.spawn(worker, mlr))
    
        gevent.joinall( tasks )
        for task in tasks:
            print task.get()
    
    if __name__ == "__main__":
        tcpus = cpu_count() * 4
        procs = []
        for id in range(0, tcpus ):
            procs.append(Process(target=task, args=()))
   
        for proc in procs:
            proc.start()
    
        for proc in procs:
            proc.join()


After upgrading to your fix, i was able to gain more speed and the exception disappeared. Very great work. You can use this code to test it yourself or, if you have redis sentinel cluster available.

**Comment by alisaifee** [comment]
Thank you for the idea and also for helping verify the change. I've merged the change to master and will make a release by EOD.
