### ISSUE TITLE
verify limits before calling

### ISSUE THREAD

**Issue by thestick613** [alisaifee/limits#8]
Apparently if you set a horrible limit, you won't be able to evaluate the script; try like this
98765432198765432198765 per 3600 seconds.
It gives a pretty nice traceback, but i seem to have lost it. I think lua data type is responsible for this, so just raise an exception when you construct the object.

**Comment by alisaifee** [comment]
The error isn't due to a lua data type but due to the limit set for redis lists. the Traceback is a bit different once the operation is carried out in a lua script, but the error is the same (`value is not an integer or out of range`).

Practically I don't think anyone would need to set a limit greater than `2^63 -1` so adding the additional check feels unnecessary.
